# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 00:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inverter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=False)),
                ('temp', models.FloatField(default=0)),
                ('on_time', models.IntegerField(default=0)),
                ('latitude', models.FloatField(default=33.3059398)),
                ('longitude', models.FloatField(default=-111.6792469)),
            ],
        ),
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_off', models.BooleanField(default=False)),
                ('generic_name', models.CharField(default=b'Mode', max_length=20)),
                ('inverter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASUi3dea.Inverter')),
            ],
        ),
        migrations.CreateModel(
            name='Pi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=33.3059398)),
                ('longitude', models.FloatField(default=-111.6792469)),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(default=0)),
                ('generic_name', models.CharField(default=b'Temperature', max_length=20)),
                ('inverter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASUi3dea.Inverter')),
            ],
        ),
        migrations.AddField(
            model_name='inverter',
            name='pi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASUi3dea.Pi'),
        ),
    ]
